spring:
  datasource:
    url: jdbc:h2:file:./db/demodb;
    #    url: jdbc:h2:mem:testdb;
    username: usertest
    password: qwerty
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    change-log: classpath:/db/changelog/changelog-master.yml

